version: '2'
services:
    blogging-app:
        image: blogging
        external_links:
            - blogging-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/blogging?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    blogging-mysql:
        extends:
            file: mysql.yml
            service: blogging-mysql
